### ISSUE TITLE
Bing ai not work anymore?

### ISSUE THREAD

**Issue by ahmadkeren** [danny-avila/node-gpt-api#15]
I already try but the API response '' (blank string)

**Comment by danny-avila** [comment]
There could be a host of reasons for this. Inspect your logs and review the open/closed issues here: 
https://github.com/waylaidwanderer/node-chatgpt-api/issues

It is working for me (on [LibreChat](https://librechat.ai))
![Making HTTP Requests in JavaScript(1)](https://github.com/danny-avila/nodejs-gpt/assets/110412045/4b12b804-ae56-4176-a640-86e25399b0ca)
